# Generated by Django 5.0.7 on 2024-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customFit', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
